### ISSUE TITLE
Lerna

### ISSUE THREAD

**Issue by steida** [rofrischmann/fela#130]
https://github.com/lerna/lerna

I suppose it would help a lot. Also, the current project structure is confusing a little. Plugins code should be where readme is.

**Comment by rofrischmann** [comment]
I had projects using this pattern, but found it's much harder to maintain compared to just having all the stuff in a single folder (just like React does it as well) But feel free to change my mind :P

**Comment by steida** [comment]
ok ok :-)

**Comment by rofrischmann** [comment]
Well, it seems legit to do this. The problem is that the versions would be much more dependent after all. Right now everything is inside the fela package, but that might also be a problem if you want to use different plugin versions e.g.

but would you put the fela core code into the `packages/fela` folder as well? or just use that pattern for plugins and stuff

**Comment by thejameskyle** [comment]
Hi @rofrischmann, the pattern encouraged by Lerna is to put all code within the `packages/` directory and allow Lerna to link everything together as if they were really installed. You can see a bunch of examples here: https://lernajs.io/#users
