### ISSUE TITLE
alternatives to `prettySelectors`?

### ISSUE THREAD

**Issue by queckezz** [rofrischmann/fela#246]
**Version**: 4.3.2
**Environment**: Both
**Type**: General

-------------------
#### Description
I saw various issues https://github.com/rofrischmann/fela/pull/104 https://github.com/rofrischmann/fela/pull/89 https://github.com/rofrischmann/fela/issues/98 advocating the use of `prettySelectors: true`. However, it seems it got completely removed. Is there any reasoning behind this?

I find it extremely helpful to see semantic atomic class names so you can take a glance at the dom node:

```html
<div class='flex flex-wrap margin-0px'>
```

It makes debugging layout issues a lot easier.

**Comment by tajo** [comment]
Check out [fela-monolithic](https://github.com/rofrischmann/fela/tree/master/packages/fela-monolithic). It makes debugging really nice.

**Comment by rofrischmann** [comment]
We had to remove it, because the API changed. We could add it to render property-value, but that comes with some challenges (e.g. prefixed props are 1 rule => 1 huge className) which I had no time to solve that days without bigger disadvantages in terms of performance and rendering flow.

I'll close this one as fela-monolithic should help out a lot. If you still think we could have a better solution, feel free to reopen that issue :)
