### ISSUE TITLE
renderToComponent

### ISSUE THREAD

**Issue by steida** [rofrischmann/fela#298]
renderToMarkup is fine, but people (me and Next.js) are using component even for HTML. 

```jsx
<html lang={currentLocale}>
  {/* yarn run favicon */}
  <Head>
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="/static/favicons/apple-touch-icon.png"
    />
    <meta
      name="viewport"
      // kihlstrom.com/2015/shrink-to-fit-no-fixes-zoom-problem-in-ios-9
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <style dangerouslySetInnerHTML={{ __html: globalStyle }} />
    {styleMarkup??? I need component}
  </Head>
```

I don't want to wrap style with another element with dangerouslySetInnerHTML. What should I do?

**Comment by steida** [comment]
Btw, do we have to call `renderer.clear()` or not?

**Comment by tajo** [comment]
Yea, I noticed that too. I am now using `<head dangerouslySetInnerHTML={{` which is not ideal (not sure if you can even do it in your case) but @rofrischmann just introduced [renderToSheetList]( https://github.com/rofrischmann/fela/blob/master/packages/fela-dom/src/server/renderToSheetList.js), so you can map it to `<style>` nodes.

Since style nodes need to stay at the first level of `<head>`, we can't wrap them with a `<div>` wrapper, so it's not possible to introduce a React component yet (React 16 will allow it) but we could provide that mapping function in the meantime. PR welcome?

**Comment by rofrischmann** [comment]
Exactly, I will have to add some tests before we can release that, but it should later work like that:
```javascript
renderer.renderToSheetList().map(({ type, media, css }) => (
  <style data-fela-type={type} media={media}>{css}</style>
))
```

**Comment by rofrischmann** [comment]
As soon as React 16 is officially released, we should reopen this issue and add the `renderToComponent` API that returns an array of react comps.

**Comment by steida** [comment]
Today.
