### ISSUE TITLE
Sorting of pseudo-class is not consistent

### ISSUE THREAD

**Issue by TxHawks** [rofrischmann/fela#473]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 6.0.x   |

-------------------
#### Description
Please try to add as much detail as possible.

#### Steps to reproduce
if I have two rules in different places in the app, called in this order:
```js
const rule1 = (props) => {
  ':hover': {color: 'red', }
  ':active':  { color: '#fff', },
}

const rule2 = (props) => {
  ':hover':  { color: '#000', },
  ':active': {color: '#fff',},
}
```

the `:active` color in `rule2` is trumped byits `:hover` rule, because it was already defined in `rule1`

#### Expected Behavior
For consistency and predictability, different pseudo-class rules should be stored in different style nodes, in the following order:
`:link`, `:visited`, `:hover`, `:focus-within`, `:focus`, `:active`

#### Actual Behavior
All rules are stored inside the same `style` node, with the `lvha` plugin only taking care of order inside the same rule.

**Comment by rofrischmann** [comment]
Got a working PoC for server-side rendering already. DOM rendering should be similar, but I am afraid it won't work with renderToNodeStream for React 16 and won't work by design at any time. Could be fixed using a plugin as well though.

**Comment by rofrischmann** [comment]
Alright, got a powerful version for DOM as well. Now need to test and bench it and find a way to leverage the order from rehydrated styles.

**Comment by TxHawks** [comment]
@rofrischmann -
Any update on this? Anything I can do to help? I'm being but by this pretty often lately.

**Comment by rofrischmann** [comment]
Huh, I need to check back on this. Lost the trace at some point, will tell tomorrow.

**Comment by dzearing** [comment]
@rofrischmann What is your solution to this problem? I'm very interested in your thoughts. I have a few ideas.

**Comment by rofrischmann** [comment]
I couldn't find any time to check back on this by now, my bad. 
I'd love to share all the ideas and stuff that already happened (there is a feature branch to check out btw.)

My core idea was to have an algorithm that calculates a score for each selector (including pseudo + @media+ @support) in order to dynamically "sort" rules. That exact score could be used to add rules at a certain place within the stylesheet (see CSSStyleSheet.insertRule parameters; 2. parameter to be precise).

The same logic would need to be applied to the clusterCache utility that is used to generate stringified CSS from a cache (for SSR e.g.)

Would also love to hear your ideas @dzearing!

**Comment by rofrischmann** [comment]
alright im going to tackle this again soon.

**Comment by dzearing** [comment]
Ah, sorry @rofrischmann for not getting back sooner!

So yes, I think calcing a score for each selector could work; it does imply that you'd need to add some complexity (which in turn might add some bundle size and maybe perf overhead.) For example when inserting new rules, you'd need to track each style element separately per score.

I am not familiar with the fela codebase (but this problem was interesting as I can see this being a general issue with the atomic css approach), so your mention of cluster cache sounds like you might already have the infra to support this idea, so maybe the overhead is negligible.

Another idea I had thought about would be to have some sort of transform on selectors which allows the consumer to increase specificity for specific scenarios. (e.g. replace `:active` with `:active:active`.) Gross hack? But maybe simpler and less bundle impact.
