### ISSUE TITLE
createComponent and connect as Components (render props)

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/fela#496]
**Type**: Feature

| Packages | Version |
| -------- | ------- |
| fela     | 6.0.x   |

-------------------
#### Description
Render props is probably the new hipster shit and to be serve the hipsters we should add them as well. 
Well and they're quite cool and useful too.

#### Proposal
We could add new APIs for both `createComponent` and `connect`.
This would have many benefits:

- no need for `passThroughProps`
- no explicit static hoisting
- better performance
- no magic
- full freedom

**Code Example**:
```javascript
import { CreateComponent } from 'react-fela'

const button = () => ({
  backgroundColor: 'grey',
  padding: 10,
  border: '1px solid black',
  fontSize: 14
})

const Button = props => (
  <CreateComponent rule={button}>
    ({ className, text }) => <div className={className}>{props.text}</div>
  <CreateComponent />
)
```

Alternatively we could have a `render` or `renderChildren` prop that is passed a render function (instead of a render function as a children)

Not sure if it really works great with createComponent, as that's one of simples HoCs possible (although we wouldn't need the `passThroughProps` anymore as we could just pass all.

The same mechanism would also apply for the `connect` use case.

**Comment by TxHawks** [comment]
I can't say how much I think this is a good API for Fela. It makes everything so much more explicit. However, I think a slightly better API for it would be:

```jsx
const MegaButton = props => (
  <FelaComponent
    rule={button]
    render={
      ({className, text, theme}) => (<Button className={className} isMega>{text}</Button>)
  />)
```

Naming the component `FelaComponent`, or anything other than `CreateComponent` really, will avoid confusion between the HOC and the component.

I think using a `render` prop is better than using `children` as a function because it is more explicit and makes it clear that the Fela component is really just there to augment existing components, not render its own markup.

Also, this is a good opportunity to pass `theme` to the underlying component. I often have breakpoints defined in the `theme`, and it's annoying to have to use `withTheme` to have theme available in the underlying component. With a render prop, I think it's okay to pass it by default.

**Comment by tajo** [comment]
> I think using a render prop is better than using children as a function because it is more explicit and makes it clear that the Fela component is really just there to augment existing components, not render its own markup.

I don't understand this argument. There is a lot of discussion about this all over the ecosystem but so far it seems as "spaces vs tab" war. Personally, I more lean to use the children prop. What happens if somebody will do this?

```jsx
<FelaComponent
    rule={button}
    render={
      ({className, text, theme}) => (<Button className={className} isMega>{text}</Button>)
    }
>
  <div>Hey</div>
</FelaComponent>
```

**Comment by TxHawks** [comment]
@tajo I agree that this is a bit of a spaces vs tabs argument (of course spaces are better than tabs and vim supperior to emacs!).

However, I find it easier to teach people new to React that a `render` prop accepts a function than it is to teach them that the `children` prop can be a function. In fact, I've found that many new to React are not even aware that `children` is an implicit prop when used inside JSX.

As to your what would happen if quedtion, the exact same that would happen if someone does:

```js
<FelaComponent
    rule={button}
    children={
      ({className, text, theme}) => (<Button className={className} isMega>{text}</Button>)
    }
>
  <div>Hey</div>
</FelaComponent>
```

`<div>Hey</div>` would win (because the third argument to `React.createElement` clobbers an explicit `children` prop.

In fact, i think this is a fine example, and that using a `render` prop over `children` allows us to simply check for the presence of a `children` prop and log a warning saying something like "that's probably not what you meant to do".

But all in all, in the grand scheme of things, I agree, it doesn't matter. This will be a great API no matter if it uses `render` or `children`
