### ISSUE TITLE
Display component name with CSSLint error in fela-plugin-validator

### ISSUE THREAD

**Issue by brianespinosa** [rofrischmann/fela#550]
#### Proposal
I love the ability to use CSSLint with the validator plugin. One issue I've noticed though is when enabling this feature in our renderer for a decent library of existing Fela components is the console error does not include the name of the component that is creating the error.

```
Invalid property "padding-left" with value "". Rule is empty. {property: "padding-left", value: ""}
```

Even when expanding the error stack trace it is not easy to see which actual component is throwing the error.

I am guessing this might also involve using [recompose](https://github.com/acdlite/recompose) to show the component name?

**Comment by rofrischmann** [comment]
I am not sure if we can actually add this in general, because fela rules do not know anything about the used component.
We might add a "magic prop" to the react-bindings that ships the displayName, but Im not a huge fan of overhead just for the sake of logs, yet I understand why its important.

@sgrishchenko @TxHawks Any ideas for this one?

**Comment by sgrishchenko** [comment]
i see 2 ways:
1) make fela-plugin-validator an enhancer 
pros:
a) it give ability pass debug information from components to user
cons: 
a) this is a very large-scale change and it will be necessary to develop a migration plan
b) it seems not very right to adjust the plugins for the needs of specific frameworks, the plugin then becomes indirectly dependent on the fel-bindings

2) to think of how to convey metainformation to the body of the style (for example with custom css property)
pros: the same as in the first case
cons: 
a) If I transmit such information in the rules, I will have to delete this information in some place, It turns out that in fela-bindings I will check if a certain plug-in is registered in the renderer and if so, in the plugin it will delete the relevant information from the rule. This will force the validator plugin to use production build.

**Comment by sgrishchenko** [comment]
there is a third option - not to support this 😊
the more I think about how difficult it will be to realize this and about the benefits it will bring, I'm increasingly inclined to the third option...

**Comment by sgrishchenko** [comment]
On the other hand: the plug-in displays a fairly detailed error and the developer chooses to suit this kind of css-rule or not. If satisfied - it can ignore these messages or disable them at the configuration level. If it does not, then the developer will have to search for case studies that he learned from the message in the whole project, regardless of which component.

**Comment by rofrischmann** [comment]
I'm closing this for now, as of today it's not really possible to implement that without direct coupling of unrelated aspects. We might get back on track with some major changes coming up that might support integrating like that, but I'm not entirely sure about it.
