### ISSUE TITLE
fela-plugin-extend crushes on undefined

### ISSUE THREAD

**Issue by EranM6** [rofrischmann/fela#657]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 6.1.7   |
| react-fela     | 7.2.0   |
| fela-plugin-extend     | 6.0.11   |

-------------------
#### Description
Passing `undefined` to the `extend` array throws a reference error about `hasOwnProperty of undefined`.

#### Steps to reproduce
```js
const style = theme => ({
  extend: [ undefined, ],
});
```

#### Expected Behavior
`undefined` should just be discarded

**Comment by TxHawks** [comment]
The culprit is [fela-plugin-extend/src/index.js#L25](https://github.com/rofrischmann/fela/blob/master/packages/fela-plugin-extend/src/index.js#L25):
```js
function extendStyle(style: Object, extension: Object): void {
  // extend conditional style objects
  if (extension.hasOwnProperty('condition')) {  // <-- This is the problem
    if (extension.condition) {
      // eslint-disable-next-line no-use-before-define
      assignStyle(style, extend(extension.style))
    }
  } else {
    // extend basic style objects
    assignStyle(style, removeUndefined(extension))
  }
}
```
It assumes `extension` is not `null` or `undefined`. All we need to do to fix this is change the condition to be  `if(extension && Object.prototype.hasOwnProperty.call(extension, "condition")) {` and we're golden since we use `removeUndefined` in the `else` clause.

Will put up a pull request that fixes it in a bit
