### ISSUE TITLE
Bug: Monolithic does not work with FelaComponent

### ISSUE THREAD

**Issue by oschade** [rofrischmann/fela#696]
**Type**: Bug / Feature / Infrastructure / Docs / Question

| Packages | Version |
| -------- | ------- |
| fela     | 10.2.1  |

-------------------
#### Description

I added `fela-monolithic` to my enhancers (with pretty-selector option). But when I use a `FelaComponent`, the name of the rule does not be added to the class-name. I think, this happens, because `FelaComponent` uses `combineRules `and `combineRules` does not combine the function names too. This should be possible by reading out the names of the combined rules and add them to the className-property or using something like

`Object.defineProperty(fn, "name", { value: combindedName })`

What do you think?

**Comment by rofrischmann** [comment]
Heyhey. I recently realised that this is true with both `FelaComponent` and `useFela` due to similar behaviour. But nowadays I think that prettySelectors was never a really reliable tool anyway as it had many prerequisites that were hard to match anyways.
I'd not want any extra code just for the sake of debugging/testing to be honest.
I think there're better ways to get nicely named components e.g. by adding a `_className: ComponentName` to the rule. It will resolve in an empty prepended className.
Seems dirty, but as fela-monolithic is only intended for testing/debugging it seems fine to me.

**Comment by TxHawks** [comment]
A somewhat ambitious alternative could be developing a devtools extension

**Comment by oschade** [comment]
Thank you for your response. Is the "_className" property on the rule already implemented? It does not work in my script. And the customClass prop on the FelaComponent triggers a deprecated warning. What is the alternative for that?

**Comment by rofrischmann** [comment]
The alternative would be to pass it to the rendered element directly rather than on FelaComponent.
The _className works with pure Atomic Design, but not sure if its in monolithic fair enough.

**Comment by oschade** [comment]
mm... yes, _className works when the monolithic enhancers is disabled. But using the "className" prop on the rendered element doenst work either with monolithic enhancer enabled.
Why do you decided to remove the _className prop? Seems like a cleaner solution to me. And it work with monolitihc.
